hostname: "csvdb.localhost"
web:
  replicaCount: 1
  repository:
    image: k3d-registry.localhost:5111/ijmacd/csvdb
  persistence:
    web_data:
      enabled: false
  tls:
    enabled: true
  ingress:
    enabled: true
  gateway:
    enabled: false
  local:
    enabled: false
