appVersion: ""
hostname: "csvdb.ijmacd.com"
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/csvdb
  persistence:
    web_data:
      enabled: true
      storage_class: local-path
      capacity: 1Gi
  tls:
    enabled: false
  local:
    enabled: false
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 10Mi
