SELECT
    CURRENT_DATE AS date,
    EXTRACT(WEEKYEAR FROM CURRENT_DATE) AS week_year,
    EXTRACT(WEEK FROM CURRENT_DATE) AS week,
    EXTRACT(WEEKDAY FROM CURRENT_DATE) AS week_day,
    EXTRACT(YEARDAY FROM CURRENT_DATE) AS year_day