apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: csvdb
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      containers:
        - name: web
          image: '{{ .Values.web.repository.image }}{{ if ne .Values.web.repository.tag "" }}:{{ .Values.web.repository.tag }}{{ end }}'
          ports:
            - name: web
              containerPort: 80
          env:
            - name: CSVDB_DATA_DIR
              value: /data
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.web.local.enabled }}
            - name: htdocs
              mountPath: /var/www/html
            - name: cgi-bin
              mountPath: /var/www/html/cgi-bin
            {{- end }}
      volumes:
        - name: data
          {{- if  .Values.web.persistence.web_data.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-web-data-{{ .Values.web.persistence.web_data.storage_class }}'
          {{ else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.web.local.enabled }}
        - name: htdocs
          hostPath:
            path: /ijmacd/csvdb/lighttpd/htdocs
        - name: cgi-bin
          hostPath:
            path: /ijmacd/csvdb/lighttpd/cgi-bin
        {{- end }}