{{ if .Values.web.persistence.web_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-web-data-{{ .Values.web.persistence.web_data.storage_class }}'
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  storageClassName: '{{ .Values.web.persistence.web_data.storage_class }}'
  resources:
    requests:
      storage: '{{ .Values.web.persistence.web_data.capacity }}'
  accessModes:
    - ReadWriteOnce
{{- end -}}